/**
 * @file cpakfs_fsck.c
 * @author Giovanni Bajo <giovannibajo@gmail.com>
 */
#include <stdint.h>
#include <errno.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include "cpak.h"
#include "cpakfs.h"
#include "cpakfs_internal.h"
#include "../utils.h"
#ifdef N64
#include "../rand_internal.h"
#endif

/** @brief Filesystem check modes */
typedef enum {
    /**
     * @brief Just mount the filesystem.
     * 
     * This function does not attempt a thorough check of the filesystem,
     * but just mount it.
     */
    MODE_MOUNT = 0,

    /**
     * @brief Check the filesystem for errors.
     * 
     * This function will scan the filesystem for errors and report them
     * using the provided report callback.
     */
    MODE_CHECK = 1,

    /**
     * @brief Fix filesystem errors.
     * 
     * This function will attempt to fix any errors found in the filesystem.
     */
    MODE_FIX = 2,
} fsck_mode_;


/** @brief Context of a mount/fsck operation */
typedef struct {
    joypad_port_t port;          ///< Joypad port number
    int mode;                    ///< Fix filesystem problems, or just check
    int nissues;                 ///< Number of issues found
    __attribute__((format(printf, 3, 4)))
    cpakfs_report_fn report;     ///< Report callback for fsck issues
} fsck_ctx_t;

static void fsid_new(cpakfs_id_t *id, int new_banks)
{
    memset(id, 0, sizeof(cpakfs_id_t));

    uint16_t fs_flags = FSFLAGS_DEFAULT; 

    __rand(id->serial, 16);
    memcpy(id->serial+16, "DRAGON", 6);
    id->serial[22] = fs_flags >> 8;
    id->serial[23] = fs_flags & 0xFF;

    id->device_id_lsb = be16(0x0001);
    id->bank_size_msb = be16(new_banks << 8);
    uint16_t checksum1, checksum2;
    __cpakfs_fsid_checksum(id, &checksum1, &checksum2);
    id->checksum1 = be16(checksum1);
    id->checksum2 = be16(checksum2);
}

static int fsck_fsid(fsck_ctx_t *ctx, cpakfs_id_t *id)
{
    bool writeback = false;

    // Read all 4 sectors
    int sec_idx[4] = { 0x20, 0x60, 0x80, 0xC0 };
    cpakfs_id_t sectors[4];
    for (int i=0; i<4; i++) {
        if (cpak_read(ctx->port, 0, sec_idx[i], sectors[i].data8, BLOCK_SIZE) < 0) {
            return -1;
        }
    }

    // Search for a valid ID sector (where the checksums match).
    cpakfs_id_t *valid = NULL;
    for (int i=0; i<4; i++) {
        // Check checksum
        uint16_t checksum1, checksum2;
        __cpakfs_fsid_checksum(&sectors[i], &checksum1, &checksum2);
        if (checksum1 == be16(sectors[i].checksum1) && checksum2 == be16(sectors[i].checksum2)) {
            valid = &sectors[i];
            break;
        }

        // Check if this is a DexDrive dump (which has a hard-coded wrong checksum)
        if (checksum1 == 0x0101 && be16(sectors[i].checksum1) == 0x0101 && be16(sectors[i].checksum2) == 0xFEFD) {
            valid = &sectors[i];
            if (ctx->report) ctx->report(CPAKFS_ISSUE_FSID_DEXDRIVE, CPAKFS_LEVEL_INFO,
                    "ID sector has a known-corrupted checksum generated by DexDrive");
            valid->checksum2 = be16(checksum2);
            writeback = true;
            break;
        }
    }

    if (valid == NULL) {
        // No valid ID sector found. We don't know which one is valid. 
        ctx->nissues++;
        if (ctx->report) ctx->report(CPAKFS_ISSUE_FSID_CHECKSUM_FAILURE, CPAKFS_LEVEL_WARNING,
                "Cannot find an ID sector with correct checksum");
                
        // If we are just mounting, we cannot proceed further.
        if (ctx->mode == MODE_MOUNT) {
            errno = ENODEV;
            return -2;
        }

        // The only information we would need to extract is how many banks this
        // cpak has. Since we cannot read the ID sector, we will try to
        // probe the cpak instead.
        // Notice that we do this even if we are not requested of fixing the errors,
        // because we need to know how many banks the cpak has in order to
        // correctly interpret the FAT. We assume the FAT might be valid even if
        // the ID sector is not.
        int num_banks = cpak_probe_banks(ctx->port);
        if (num_banks < 0) return -1;

        // Create a valid ID sector from scratch (and actually write it back if needed).
        valid = &sectors[0];
        fsid_new(valid, num_banks);
        writeback = true;
    } else  if (ctx->mode >= MODE_CHECK) {
        // A valid ID sector was found. Check whether it matches all the copies
        for (int i=0; i<4; i++) {
            if (memcmp(valid->data8, sectors[i].data8, BLOCK_SIZE) != 0) {
                // This copy is different from the valid one. If we are fixing,
                // we will write back the valid copy to this sector.
                if (ctx->report) ctx->report(CPAKFS_ISSUE_FSID_CORRUPTED_BACKUP, CPAKFS_LEVEL_INFO,
                        "ID sector backup is corrupted (can be recovered from main)");
                writeback = true;
            }
        }
    }

    // Check if the device ID is valid. This is just advisory
    if (ctx->mode >= MODE_CHECK && (be16(valid->device_id_lsb) & 0x01) != 0x01) {
        if (ctx->report) ctx->report(CPAKFS_ISSUE_FSID_WRONG_DEVICE_ID, CPAKFS_LEVEL_INFO,
            "Device ID is not valid (%04X); this is just advisory so it can be ignored", be16(valid->device_id_lsb));
        valid->device_id_lsb = be16(0x01);
        writeback = true;
    }

    // Check if writeback is needed. If so (and we are in fix mode),
    // write the valid ID sector back to all 4 sectors.
    if (writeback && ctx->mode == MODE_FIX) {
        for (int i=0; i<4; i++) {
            if (cpak_write(ctx->port, 0, sec_idx[i], valid->data8, BLOCK_SIZE) < 0) {
                return -1;
            }
        }
    }

    // Copy the valid ID sector to the output
    memcpy(id, valid, BLOCK_SIZE);
    return 0;
}

/**
 * @brief Check and fix the FAT of a cpak filesystem.
 * 
 * @param ctx           The fsck context containing the port and fix options
 * @param fsid          A known-valid ID sector
 * @param out_fat       Pointer to store the FAT data
 * @return int          0 on success, negative on error
 */
static int fsck_fat(fsck_ctx_t *ctx, cpakfs_id_t* fsid, cpakfs_fat_entry_t **out_fat)
{
    // Allocate memory for the FAT
    int fat_size = be16(fsid->bank_size_msb) & 0xFF00;
    int reserved = 1 + (fat_size >> 8) * 2 + 2; // Reserved pages: ID sector, two FAT copies, note table
    cpakfs_fat_entry_t *fat = malloc(be16(fsid->bank_size_msb) & 0xFF00);
    int count_main_backup = 0;
    uint64_t fat_dirty = 0;
    int retcode = -1;
    cpakfs_fat_entry_t backup[128];

    // Read the main FAT copy in one block read
    if (cpak_read(ctx->port, 0, 0x100, fat, fat_size) < 0) goto exit;

    // Verify checksum of each FAT page.
    for (int i=0; i<fat_size; i+=PAGE_SIZE) {
        // Read backup copy
        if (cpak_read(ctx->port, 0, 0x100 + fat_size + i, backup, PAGE_SIZE) < 0) goto exit;

        // While the checksum was designed to be calculated over the whole page saving
        // for the checksum entry itself, in many cpak images the checksum seems to be
        // computed skipping the reserved entries in the first page.
        // Those entries should be 0 anyway.
        int csum_start_idx = (i == 0) ? reserved : 1;

        // Check checksum. We calculate it over the whole page as expected, but if it
        // fails, we also try ignoring the reserved pages in case they erroneously
        // contain non-zero entries. We found cpak images around that had the
        // checksum calculated like this.
        bool main_csum_ok = __cpakfs_fat_checksum(fat + i/2, csum_start_idx) == fat[i/2].page;
        bool backup_csum_ok = __cpakfs_fat_checksum(backup, csum_start_idx) == backup[0].page;

        if (!main_csum_ok && !backup_csum_ok) {
            ctx->nissues++;
            if (ctx->report) ctx->report(CPAKFS_ISSUE_FAT_CHECKSUM_FAILURE, CPAKFS_LEVEL_ERROR,
                    "FAT page at 0x%x/0x%x has invalid checksum", 0x100+i, 0x100+fat_size+i);

            // The best we can do now is to still keep either of the copies, hoping for the best.
            // We keep the page coming from the copy that is being used most.
            if (count_main_backup < 0)
                memcpy(fat + i/2, backup, PAGE_SIZE);
        } else {
            // Report unsynchronized FAT copies
            if (memcmp(fat + i/2, backup, PAGE_SIZE) != 0) {
                if (ctx->report) ctx->report(CPAKFS_ISSUE_FAT_UNSYNCHRONIZED, CPAKFS_LEVEL_INFO,
                        "FAT page at 0x%x/0x%x has unsynchronized copies", 0x100+i, 0x100+fat_size+i);

                // If we are in fix mode, write back this page to synchronize the copies.
                if (ctx->mode == MODE_FIX) fat_dirty |= ((uint64_t)1 << (i >> 7));
            }

            // At least one of the FAT copies is valid. Keep the good one.
            if (main_csum_ok) {
                count_main_backup++;
            } else {
                memcpy(fat + i/2, backup, PAGE_SIZE);
                count_main_backup--;
            }
        }
    }

    if (ctx->mode >= MODE_CHECK) {
        int reserved = 1 + (be16(fsid->bank_size_msb) >> 8) * 2 + 2;

        for (int i=0; i < fat_size/2; i++) {
            if ((i & 0x7F) == 0) // skip checksums
                continue;
            
            if (i < reserved) {
                // Entries for reserved pages should be 0
                if (!FAT_IS_RESERVED(fat[i])) {
                    if (ctx->report) ctx->report(CPAKFS_ISSUE_FAT_INVALID_RESERVED, CPAKFS_LEVEL_INFO,
                            "Reserved page %d has an invalid FAT entry (0x%02x%02x)", i, fat[i].bank, fat[i].page);
                    fat[i] = FAT_RESERVED;
                    fat_dirty |= ((uint64_t)1 << (i >> 7));
                }
            // If a potentially valid page is neither a valid, terminator, or unused entry,
            // we need to report it as an error.
            } else if (!FAT_IS_VALID(fat[i], reserved) && !FAT_IS_TERMINATOR(fat[i]) && !FAT_IS_UNUSED(fat[i])) {
                ctx->nissues++;
                if (ctx->report) ctx->report(CPAKFS_ISSUE_FAT_INVALID_RESERVED, CPAKFS_LEVEL_ERROR,
                        "FAT entry for page %d is reserved but has invalid value (%02x%02x)", i, fat[i].bank, fat[i].page);

                // Since we can't know whether this is a valid page or not, we will
                // mark it as unused, so that it can be allocated later.
                fat[i] = FAT_UNUSED;
                fat_dirty |= ((uint64_t)1 << (i >> 7));
            }

            // Check if the bank number is valid. The bank number should be lower
            // than the number of banks in the pak, as recorded by the fsid.
            if (FAT_IS_VALID(fat[i], reserved) && fat[i].bank >= be16(fsid->bank_size_msb) >> 8) {
                ctx->nissues++;
                if (ctx->report) ctx->report(CPAKFS_ISSUE_FAT_INVALID_BANK, CPAKFS_LEVEL_ERROR,
                        "FAT entry for page %d has invalid bank number (%d)", i, fat[i].bank);
                fat[i] = FAT_UNUSED;
                fat_dirty |= ((uint64_t)1 << (i >> 7));
            }
        }
    }

    if (ctx->mode == MODE_FIX) {
        for (int i=0; i<64 && fat_dirty; i++) {
            if (fat_dirty & (1 << i)) {
                cpakfs_fat_entry_t *fat_page = fat + i*128;

                // Update checksum
                uint8_t checksum = __cpakfs_fat_checksum(fat_page, 1);
                fat_page[0] = (cpakfs_fat_entry_t){0, checksum};

                // Write both copies of the FAT page. Try writing both copies, before
                // giving up, in case one of them is non writable for some hardware reason.
                bool done = false;
                if (cpak_write(ctx->port, 0, 0x100 + 0*fat_size + i*PAGE_SIZE, fat_page, PAGE_SIZE) >= 0) done = true;
                if (cpak_write(ctx->port, 0, 0x100 + 1*fat_size + i*PAGE_SIZE, fat_page, PAGE_SIZE) >= 0) done = true;
                if (!done) goto exit;

                fat_dirty &= ~(1 << i);
            }
        }
    }

    // We have a valid or at least workable FAT. Proceed.
    retcode = 0;

exit:
    if (retcode < 0)
        free(fat);
    else
        *out_fat = fat;
    return retcode;
}

/** Maximum number of orphaned notes to track*/
#define MAX_ORPHAN_NOTES            64
/** Number of bitset words per bank */
#define WORDS_PER_BANK              (NUM_PAGES / 64)
/** Set a bit in a FAT bitset */
#define BIT_SET(bitset, entry)      ((bitset)[(entry).bank][(entry).page >> 6] |= (1ULL << ((entry).page & 63)))
/** Test a bit in a FAT bitset */
#define BIT_TEST(bitset, entry)     (((bitset)[(entry).bank][(entry).page >> 6] >> ((entry).page & 63)) & 1)

static int fsck_chains(fsck_ctx_t *ctx, int num_banks, cpakfs_fat_entry_t fat[][NUM_PAGES], cpakfs_fat_entry_t roots[MAX_NOTES], int nroots)
{
    int reserved = 1 + (num_banks * 2) + 2;
    
    // Allocate 2D bitsets: [bank][word] where each word covers 64 pages
    uint64_t (*visited)[WORDS_PER_BANK] = calloc(num_banks, sizeof(*visited));
    uint64_t (*processed)[WORDS_PER_BANK] = calloc(num_banks, sizeof(*processed));
    if (!visited || !processed) return -1;
    
    // Phase 1: Validate existing root chains
    for (int i = 0; i < nroots; i++) {
        cpakfs_fat_entry_t current = roots[i];
        
        while (true) {
            // Check for infinite loop
            if (BIT_TEST(visited, current)) {
                ctx->nissues++;
                if (ctx->report) ctx->report(CPAKFS_ISSUE_CHAIN_INFINITE_LOOP, CPAKFS_LEVEL_ERROR,
                    "Chain %d has infinite loop at page %02x:%02x", i, current.bank, current.page);
                break;
            }
            
            // Mark as visited and get next entry
            BIT_SET(visited, current);
            cpakfs_fat_entry_t next = fat[current.bank][current.page];
            
            if (FAT_IS_TERMINATOR(next)) break;
            
            if (!FAT_IS_VALID(next, reserved)) {
                ctx->nissues++;
                if (ctx->report) ctx->report(CPAKFS_ISSUE_CHAIN_NO_TERMINATOR, CPAKFS_LEVEL_ERROR,
                    "Chain %d does not end with terminator (invalid entry %02x:%02x)", 
                    i, next.bank, next.page);
                break;
            }
            
            current = next;
        }
    }
    
    // Phase 2: Find and reconstruct orphaned chains
    cpakfs_fat_entry_t orphan_roots[MAX_ORPHAN_NOTES];
    int16_t orphan_len[MAX_ORPHAN_NOTES];
    int num_orphan_roots = 0;
    
    for (int bank = 0; bank < num_banks; bank++) {
        for (int page = reserved; page < NUM_PAGES; page++) {
            cpakfs_fat_entry_t current = {bank, page};
            
            // Skip if already processed or not orphaned
            if (BIT_TEST(visited, current) || BIT_TEST(processed, current) || 
                FAT_IS_UNUSED(fat[bank][page])) continue;
            
            // Found orphaned page - follow chain forward to validate and mark
            cpakfs_fat_entry_t chain_start = current;
            int chain_len = 0;
            
            while (true) {
                if (BIT_TEST(processed, current)) {
                    // Hit already processed orphan - check if it's an existing root
                    for (int j = 0; j < num_orphan_roots; j++) {
                        if (orphan_roots[j].bank == current.bank && orphan_roots[j].page == current.page) {
                            // Update existing root with earlier start and new total length
                            orphan_roots[j] = chain_start;
                            orphan_len[j] = chain_len + orphan_len[j];
                            goto next_page;
                        }
                    }
                    // Collision with another orphaned chain that doesn't have a known root
                    ctx->nissues++;
                    if (ctx->report) ctx->report(CPAKFS_ISSUE_CHAIN_COLLISION, CPAKFS_LEVEL_ERROR,
                        "Orphaned chain at %02x:%02x collides with another orphaned chain at %02x:%02x", 
                        chain_start.bank, chain_start.page, current.bank, current.page);
                    break;
                }
                
                // Check for collision with legitimate chains
                if (BIT_TEST(visited, current)) {
                    ctx->nissues++;
                    if (ctx->report) ctx->report(CPAKFS_ISSUE_CHAIN_COLLISION, CPAKFS_LEVEL_ERROR,
                        "Orphaned chain at %02x:%02x collides with legitimate chain at %02x:%02x", 
                        chain_start.bank, chain_start.page, current.bank, current.page);
                    break;
                }
                
                BIT_SET(processed, current);
                chain_len++;
                
                cpakfs_fat_entry_t next = fat[current.bank][current.page];
                if (FAT_IS_TERMINATOR(next)) break;
                
                if (!FAT_IS_VALID(next, reserved)) {
                    ctx->nissues++;
                    if (ctx->report) ctx->report(CPAKFS_ISSUE_CHAIN_NO_TERMINATOR, CPAKFS_LEVEL_ERROR,
                        "Orphaned chain at %02x:%02x does not end with terminator", 
                        chain_start.bank, chain_start.page);
                    break;
                }
                
                current = next;
            }
            
            // Add new orphaned root
            if (num_orphan_roots < MAX_ORPHAN_NOTES) {
                orphan_roots[num_orphan_roots] = chain_start;
                orphan_len[num_orphan_roots] = chain_len;
                num_orphan_roots++;
            }
            
            next_page:;
        }
    }
    
    // Report orphaned chains now that they are definitively identified
    for (int i = 0; i < num_orphan_roots; i++) {
        if (ctx->report) ctx->report(CPAKFS_ISSUE_CHAIN_ORPHANED, CPAKFS_LEVEL_WARNING,
            "Orphaned chain found at %02x:%02x (length %d)", 
            orphan_roots[i].bank, orphan_roots[i].page, orphan_len[i]);
    }
    
    // Phase 3: Select longest orphaned chains and append to roots
    int max_to_add = MAX_NOTES - nroots;
    if (max_to_add > num_orphan_roots) max_to_add = num_orphan_roots;
    
    // Iteratively find longest chain, add it to roots, and remove it from orphan_roots
    for (int added = 0; added < max_to_add; added++) {
        // Find index of longest remaining orphaned chain
        int longest_idx = 0;
        for (int i = 1; i < num_orphan_roots; i++) {
            if (orphan_len[i] > orphan_len[longest_idx]) {
                longest_idx = i;
            }
        }
        
        // Add longest chain to roots
        roots[nroots++] = orphan_roots[longest_idx];
        
        // Remove it by swapping with last element and decreasing count
        if (longest_idx != num_orphan_roots - 1) {
            SWAP(orphan_roots[longest_idx], orphan_roots[num_orphan_roots - 1]);
            SWAP(orphan_len[longest_idx], orphan_len[num_orphan_roots - 1]);
        }
        num_orphan_roots--;
    }
    
    free(visited);
    free(processed);
    return num_orphan_roots;
}

static int fsck_notes(fsck_ctx_t *ctx, cpakfs_id_t* fsid, cpakfs_fat_entry_t *fat)
{
    int fat_size = be16(fsid->bank_size_msb) & 0xFF00;
    int reserved = 1 + (fat_size >> 8) * 2 + 2; // Reserved pages: ID sector, two FAT copies, note table
    const int note_start = 0x100 + fat_size * 2;
    uint16_t note_dirty = 0;
    cpakfs_fat_entry_t roots[MAX_NOTES]; int nroots = 0;

    // Read all notes
    cpakfs_note_t notes[MAX_NOTES];
    if (cpak_read(ctx->port, 0, note_start, notes, sizeof(notes)) < 0)
        return -1;

    for (int i=0; i<MAX_NOTES; i++) {
        cpakfs_note_t *note = &notes[i];
        uint16_t status = be16(note->status);
        bool occupied = (status & NOTE_STATUS_OCCUPIED) != 0;

        // Gamecode and pubcode are ASCII most of the time, but Datel Gameshark
        // saves binary codes in there. So what we just consider as invalid
        // is full zeros.
        if (occupied &&
            note->gamecode[0] == 0 && note->gamecode[1] == 0 &&
            note->gamecode[2] == 0 && note->gamecode[3] == 0) {
            ctx->nissues++;
            if (ctx->report) ctx->report(CPAKFS_ISSUE_NOTE_INVALID_GAMECODE, CPAKFS_LEVEL_ERROR,
                    "Note %d has invalid gamecode: %02x%02x%02x%02x", i,
                    note->gamecode[0], note->gamecode[1],
                    note->gamecode[2], note->gamecode[3]);
            if (ctx->mode == MODE_FIX) {
                memset(note, 0, sizeof(cpakfs_note_t));
                note_dirty |= (1 << i);
            }
        }

        if (occupied &&
            note->pubcode[0] == 0 && note->pubcode[1] == 0) {
            ctx->nissues++;
            if (ctx->report) ctx->report(CPAKFS_ISSUE_NOTE_INVALID_PUBCODE, CPAKFS_LEVEL_ERROR,
                    "Note %d has invalid publisher code: %02x%02x", i,
                    note->pubcode[0], note->pubcode[1]);
            if (ctx->mode == MODE_FIX) {
                memset(note, 0, sizeof(cpakfs_note_t));
                note_dirty |= (1 << i);
            }
        }

        // Check if the first page is valid
        if (occupied && !FAT_IS_VALID(note->first_page, reserved)) {
            ctx->nissues++;
            if (ctx->report) ctx->report(CPAKFS_ISSUE_NOTE_INVALID_FIRST_PAGE, CPAKFS_LEVEL_ERROR,
                    "Note %d has invalid first page: %02x%02x", i,
                    note->first_page.bank, note->first_page.page);
            if (ctx->mode == MODE_FIX) {
                // If the first page is invalid, we cannot fix it, so we just
                // clear the note.
                memset(note, 0, sizeof(cpakfs_note_t));
                note_dirty |= (1 << i); 
            }
        }

        if (FAT_IS_VALID(note->first_page, reserved)) 
            roots[nroots++] = note->first_page;
    }

    // Check and fix chains
    fsck_chains(ctx, be16(fsid->bank_size_msb) >> 8, (cpakfs_fat_entry_t (*)[NUM_PAGES])fat, roots, nroots);

    return 0;
}

int cpakfs_fsck(joypad_port_t port, bool fix_errors, cpakfs_report_fn report)
{
    int err;

    joypad_accessory_type_t type = joypad_get_accessory_type(port);
    if (type != JOYPAD_ACCESSORY_TYPE_CONTROLLER_PAK) {
        errno = ENODEV;
        return -1;
    }

    fsck_ctx_t ctx = {
        .port = port,
        .mode = fix_errors ? MODE_FIX : MODE_CHECK,
        .report = report,
    };

    // Check and fix the sector ID
    cpakfs_id_t fsid;
    err = fsck_fsid(&ctx, &fsid);
    if (err < 0) return err;

    // Check and fix the FAT
    cpakfs_fat_entry_t *fat = NULL;
    err = fsck_fat(&ctx, &fsid, &fat);
    if (err < 0) return err;

    // Check and fix notes
    err = fsck_notes(&ctx, &fsid, fat);
    if (err < 0) return err; 
    
    free(fat);
    return ctx.nissues;
}

int cpakfs_format(joypad_port_t port, bool erase)
{
    joypad_accessory_type_t type = joypad_get_accessory_type(port);
    if (type != JOYPAD_ACCESSORY_TYPE_CONTROLLER_PAK) {
        errno = ENODEV;
        return -1;
    }

    // Detect the number of banks
    int num_banks = cpak_probe_banks(port);
    if (num_banks < 0) return -1;

    // Create a new fresh ID sector
    cpakfs_id_t fsid;
    fsid_new(&fsid, num_banks);

    // Emtpy page to write
    uint8_t empty[PAGE_SIZE] = {0};

    // Write the whole ID page. Write fsid only in the blocks that are supposed
    // to contain it, otherwise just clear.
    for (int i=0; i<8; i++) {
        uint8_t *data = (0x5A & (1<<i)) ? fsid.data8 : empty;
        if (cpak_write(port, 0, i * BLOCK_SIZE, data, BLOCK_SIZE) < 0)
            return -1;
    }

    // First page of the FAT shows reserved pages
    int fat_size = be16(fsid.bank_size_msb) & 0xFF00;
    cpakfs_fat_entry_t fat[128];
    int reserved = 1 + (fat_size >> 8) * 2 + 2;

    for (int i=0; i<reserved; i++)
        fat[i] = FAT_RESERVED;
    for (int i=reserved; i<128; i++)
        fat[i] = FAT_UNUSED;

    uint8_t checksum = __cpakfs_fat_checksum(fat, 1);
    fat[0] = (cpakfs_fat_entry_t){0, checksum};

    // Write the FAT to both copies
    if (cpak_write(port, 0, 0x100 + 0*fat_size, fat, PAGE_SIZE) < 0)
        return -1;
    if (cpak_write(port, 0, 0x100 + 1*fat_size, fat, PAGE_SIZE) < 0)
        return -1;

    // Now write subsequent pages as empty
    if (num_banks > 1) {
        for (int i=0; i<reserved; i++)
            fat[i] = FAT_UNUSED;
        checksum = __cpakfs_fat_checksum(fat, 1);
        fat[0] = (cpakfs_fat_entry_t){0, checksum};

        for (int i=1; i<num_banks; i++) {
            if (cpak_write(port, 0, 0x100 + 0*fat_size + i*PAGE_SIZE, fat, PAGE_SIZE) < 0)
                return -1;
            if (cpak_write(port, 0, 0x100 + 1*fat_size + i*PAGE_SIZE, fat, PAGE_SIZE) < 0)
                return -1;
        }
    }

    // Finally, write the note table as fully empty.
    if (cpak_write(port, 0, 0x100 + 2*fat_size + 0*PAGE_SIZE, empty, PAGE_SIZE) < 0)
        return -1;
    if (cpak_write(port, 0, 0x100 + 2*fat_size + 1*PAGE_SIZE, empty, PAGE_SIZE) < 0)
        return -1;

    if (erase) {
        // Erase all pages in all banks
        int addr = 0x100 + 2*fat_size + 2*PAGE_SIZE;
        int end = BANK_SIZE;

        while (addr < end) {
            if (cpak_write(port, addr >> 15, addr & 0x7FFF, empty, PAGE_SIZE) < 0)
                return -1;
            addr += PAGE_SIZE;
        }
    }

    return 0;
}
