/**
 * @file cpak_fsck.c
 * @author Giovanni Bajo <giovannibajo@gmail.com>
 */
#include <stdint.h>
#include <errno.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include "cpak.h"
#include "cpak_internal.h"
#ifdef N64
#include "../rand_internal.h"
#endif

/** @brief Filesystem check modes */
typedef enum {
    /**
     * @brief Just mount the filesystem.
     * 
     * This function does not attempt a thorough check of the filesystem,
     * but just mount it.
     */
    MODE_MOUNT = 0,

    /**
     * @brief Check the filesystem for errors.
     * 
     * This function will scan the filesystem for errors and report them
     * using the provided report callback.
     */
    MODE_CHECK = 1,

    /**
     * @brief Fix filesystem errors.
     * 
     * This function will attempt to fix any errors found in the filesystem.
     */
    MODE_FIX = 2,
} fsck_mode_;


/** @brief Context of a mount/fsck operation */
typedef struct {
    joypad_port_t port;          ///< Joypad port number
    int mode;                    ///< Fix filesystem problems, or just check
    __attribute__((format(printf, 3, 4)))
    cpakfs_report_fn report;     ///< Report callback for fsck issues
} fsck_ctx_t;

/* 
 * Probe the cpak to find out the total number of banks.
 * NOTE: this function assumes that the cpak is a multi-bank cpak, which
 * correctly support bank switching (albeit the behavior is undefined if
 * the wrong bank number is accessed).
 */
static int probe_banks(joypad_port_t port)
{
    int retcode = -1;
    uint8_t* save_label = malloc(MAX_BANKS * BLOCK_SIZE);

    // Create a random probe label that we will use to mark banks that we have already probed.
    uint8_t probe_label[BLOCK_SIZE];
    __rand(probe_label, BLOCK_SIZE);

    int bnk;
    for (bnk = 0; bnk < MAX_BANKS; bnk++) {

        // Read the current label into the save area
        if (block_read(port, bnk * BANK_SIZE, save_label + bnk * BLOCK_SIZE, BLOCK_SIZE) < 0) {
            goto exit;
        }

        // If the label matches the probe label, it means that an already probed
        // bank was selected (no need to restore it as it doesn't exist).
        if (bnk > 0 && memcmp(save_label + bnk * BLOCK_SIZE, probe_label, BLOCK_SIZE) == 0)
            break;

        // Write the probe label to the current bank
        if (block_write(port, bnk * BANK_SIZE, probe_label, BLOCK_SIZE) < 0) {
            goto exit;
        }
    }

    // Return the number of banks found
    retcode = bnk;

exit:
    for (int i=0; i<bnk; i++) {
        // Restore the label area in the first page of each bank. Normally this
        // area is unused anyway and can be safely corrupted, but we do this
        // to preserve also the functionality of custom filesystems that might
        // instead use those areas.
        // Do a best effort, ignoring I/O errors.
        block_write(port, i * BANK_SIZE, save_label + i * BLOCK_SIZE, BLOCK_SIZE);
    }

    free(save_label);
    return retcode;
}

static void fsid_new(cpakfs_id_t *id, int new_banks)
{
    memset(id, 0, sizeof(cpakfs_id_t));

    uint16_t fs_flags = FSFLAGS_DEFAULT; 

    __rand(id->serial, 16);
    memcpy(id->serial+16, "DRAGON", 6);
    id->serial[22] = fs_flags >> 8;
    id->serial[23] = fs_flags & 0xFF;

    id->device_id_lsb = be16(0x0001);
    id->bank_size_msb = be16(new_banks << 8);
    uint16_t checksum1, checksum2;
    __cpak_fsid_checksum(id, &checksum1, &checksum2);
    id->checksum1 = be16(checksum1);
    id->checksum2 = be16(checksum2);
}

static int fsck_fsid(fsck_ctx_t *ctx, cpakfs_id_t *id)
{
    bool writeback = false;

    // Read all 4 sectors
    int sec_idx[4] = { 0x20, 0x60, 0x80, 0xC0 };
    cpakfs_id_t sectors[4];
    for (int i=0; i<4; i++) {
        if (block_read(ctx->port, sec_idx[i], sectors[i].data8, BLOCK_SIZE) < 0) {
            return -1;
        }
    }

    // Search for a valid ID sector (where the checksums match).
    cpakfs_id_t *valid = NULL;
    for (int i=0; i<4; i++) {
        // Check checksum
        uint16_t checksum1, checksum2;
        __cpak_fsid_checksum(&sectors[i], &checksum1, &checksum2);
        if (checksum1 == be16(sectors[i].checksum1) && checksum2 == be16(sectors[i].checksum2)) {
            valid = &sectors[i];
            break;
        }

        // Check if this is a DexDrive dump (which has a hard-coded wrong checksum)
        if (checksum1 == 0x0101 && be16(sectors[i].checksum1) == 0x0101 && be16(sectors[i].checksum2) == 0xFEFD) {
            valid = &sectors[i];
            if (ctx->report) ctx->report(CPAKFS_ISSUE_FSID_DEXDRIVE, CPAKFS_LEVEL_INFO,
                    "ID sector has a known-corrupted checksum generated by DexDrive");
            valid->checksum2 = be16(checksum2);
            writeback = true;
            break;
        }
    }

    if (valid == NULL) {
        // No valid ID sector found. We don't know which one is valid. 
        if (ctx->report) ctx->report(CPAKFS_ISSUE_FSID_CHECKSUM_FAILURE, CPAKFS_LEVEL_WARNING,
                "Cannot find an ID sector with correct checksum");
                
        // If we are just mounting, we cannot proceed further.
        if (ctx->mode == MODE_MOUNT) {
            errno = ENODEV;
            return -2;
        }

        // The only information we would need to extract is how many banks this
        // cpak has. Since we cannot read the ID sector, we will try to
        // probe the cpak instead.
        // Notice that we do this even if we are not requested of fixing the errors,
        // because we need to know how many banks the cpak has in order to
        // correctly interpret the FAT. We assume the FAT might be valid even if
        // the ID sector is not.
        int num_banks = probe_banks(ctx->port);
        if (num_banks < 0) return -1;

        // Create a valid ID sector from scratch (and actually write it back if needed).
        valid = &sectors[0];
        fsid_new(valid, num_banks);
        writeback = true;
    } else  if (ctx->mode >= MODE_CHECK) {
        // A valid ID sector was found. Check whether it matches all the copies
        for (int i=0; i<4; i++) {
            if (memcmp(valid->data8, sectors[i].data8, BLOCK_SIZE) != 0) {
                // This copy is different from the valid one. If we are fixing,
                // we will write back the valid copy to this sector.
                if (ctx->report) ctx->report(CPAKFS_ISSUE_FSID_CORRUPTED_BACKUP, CPAKFS_LEVEL_INFO,
                        "ID sector backup is corrupted (can be recovered from main)");
                writeback = true;
            }
        }
    }

    // Check if the device ID is valid. This is just advisory
    if (ctx->mode >= MODE_CHECK && (be16(valid->device_id_lsb) & 0x01) != 0x01) {
        if (ctx->report) ctx->report(CPAKFS_ISSUE_FSID_WRONG_DEVICE_ID, CPAKFS_LEVEL_INFO,
            "Device ID is not valid (%04X); this is just advisory so it can be ignored", be16(valid->device_id_lsb));
        valid->device_id_lsb = be16(0x01);
        writeback = true;
    }

    // Check if writeback is needed. If so (and we are in fix mode),
    // write the valid ID sector back to all 4 sectors.
    if (writeback && ctx->mode == MODE_FIX) {
        for (int i=0; i<4; i++) {
            if (block_write(ctx->port, sec_idx[i], valid->data8, BLOCK_SIZE) < 0) {
                return -1;
            }
        }
    }

    // Copy the valid ID sector to the output
    memcpy(id, valid, BLOCK_SIZE);
    return 0;
}

/** 
 * @brief Compute the checksum of a FAT page, starting from a given entry index. 
 */
static uint8_t fat_page_checksum(cpakfs_fat_entry_t *fat_page, int start_idx)
{
    uint8_t checksum = 0;
    for (int i=start_idx; i<128; i++) {
        checksum += fat_page[i].bank;
        checksum += fat_page[i].page;
    }
    return checksum;
}

/**
 * @brief Check and fix the FAT of a cpak filesystem.
 * 
 * @param ctx           The fsck context containing the port and fix options
 * @param fsid          A known-valid ID sector
 * @param out_fat       Pointer to store the FAT data
 * @return int          0 on success, negative on error
 */
static int fsck_fat(fsck_ctx_t *ctx, cpakfs_id_t* fsid, cpakfs_fat_entry_t **out_fat)
{
    // Allocate memory for the FAT
    int fat_size = be16(fsid->bank_size_msb) & 0xFF00;
    int reserved = 1 + (fat_size >> 8) * 2 + 2; // Reserved pages: ID sector, two FAT copies, note table
    cpakfs_fat_entry_t *fat = malloc(be16(fsid->bank_size_msb) & 0xFF00);
    int count_main_backup = 0;
    uint64_t fat_dirty = 0;
    int retcode = -1;

    // Read the main FAT copy in one block read
    if (block_read(ctx->port, 0x100, fat, fat_size) < 0) goto exit;

    // Verify checksum of each FAT page. If the checksum is wrong, read the
    // backup copy
    for (int i=0; i<fat_size; i+=PAGE_SIZE) {
        // While the checksum was designed to be calculated over the whole page saving
        // for the checksum entry itself, in many cpak images the checksum seems to be
        // computed skipping the reserved entries in the first page.
        // Those entries should be 0 anyway.
        int csum_start_idx = (i == 0) ? reserved : 1;

        // Check checksum. We calculate it over the whole page as expected, but if it
        // fails, we also try ignoring the reserved pages in case they erroneously
        // contain non-zero entries. We found cpak images around that had the
        // checksum calculated like this.
        if (fat_page_checksum(fat + i/2, csum_start_idx) == fat[i/2].page) {
            count_main_backup++;
        } else {
            cpakfs_fat_entry_t backup[128];

            // Check backup copy
            if (block_read(ctx->port, 0x100 + fat_size + i, backup, PAGE_SIZE) < 0) goto exit;

            // Verify backup copy checksum
            if (fat_page_checksum(backup, csum_start_idx) == backup[0].page) {
                memcpy(fat + i/2, backup, PAGE_SIZE);
                count_main_backup--;
            } else {
                if (ctx->report) ctx->report(CPAKFS_ISSUE_FAT_CHECKSUM_FAILURE, CPAKFS_LEVEL_ERROR,
                        "FAT page at 0x%x/0x%x has invalid checksum", 0x100+i, 0x100+fat_size+i);

                if (ctx->mode == MODE_MOUNT) {
                    // If we are just mounting, we cannot proceed further.
                    errno = ENODEV;
                    retcode = -3;
                    goto exit;
                }

                // The best we can do now is to still keep either of the copies, hoping for the best.
                // We keep the page coming from the copy that is being used most.
                if (count_main_backup < 0)
                    memcpy(fat + i/2, backup, PAGE_SIZE);                
            }
        }
    }

    if (ctx->mode >= MODE_CHECK) {
        int reserved = 1 + (be16(fsid->bank_size_msb) >> 8) * 2 + 2;

        for (int i=0; i < fat_size/2; i++) {
            if ((i & 0x7F) == 0) // skip checksums
                continue;
            
            if (i < reserved) {
                // Entries for reserved pages should be 0
                if (!FAT_IS_RESERVED(fat[i])) {
                    if (ctx->report) ctx->report(CPAKFS_ISSUE_FAT_INVALID_RESERVED, CPAKFS_LEVEL_INFO,
                            "Reserved page %d has an invalid FAT entry (0x%02x%02x)", i, fat[i].bank, fat[i].page);
                    if (ctx->mode == MODE_FIX) {
                        fat[i] = FAT_RESERVED;
                        fat_dirty |= ((uint64_t)1 << (i >> 7));
                    }
                }
            // If a potentially valid page is neither a valid, terminator, or unused entry,
            // we need to report it as an error.
            } else if (!FAT_IS_VALID(fat[i], reserved) && !FAT_IS_TERMINATOR(fat[i]) && !FAT_IS_UNUSED(fat[i])) {
                if (ctx->report) ctx->report(CPAKFS_ISSUE_FAT_INVALID_RESERVED, CPAKFS_LEVEL_ERROR,
                        "FAT entry for page %d is reserved but has invalid value (%02x%02x)", i, fat[i].bank, fat[i].page);

                // Since we can't know whether this is a valid page or not, we will
                // mark it as unused, so that it can be allocated later.
                if (ctx->mode == MODE_FIX) {
                    fat[i] = FAT_UNUSED;
                    fat_dirty |= ((uint64_t)1 << (i >> 7));
                }
            }
        }
    }

    if (ctx->mode == MODE_FIX) {
        for (int i=0; i<64 && fat_dirty; i++) {
            if (fat_dirty & (1 << i)) {
                cpakfs_fat_entry_t *fat_page = fat + i*128;

                // Update checksum
                uint8_t checksum = fat_page_checksum(fat_page, 1);
                fat_page[0] = (cpakfs_fat_entry_t){0, checksum};

                // Write both copies of the FAT page. Try writing both copies, before
                // giving up, in case one of them is non writable for some hardware reason.
                bool done = false;
                if (block_write(ctx->port, 0x100 + 0*fat_size + i*PAGE_SIZE, fat_page, PAGE_SIZE) >= 0) done = true;
                if (block_write(ctx->port, 0x100 + 1*fat_size + i*PAGE_SIZE, fat_page, PAGE_SIZE) >= 0) done = true;
                if (!done) goto exit;

                fat_dirty &= ~(1 << i);
            }
        }
    }

    // We have a valid or at least workable FAT. Proceed.
    retcode = 0;

exit:
    if (retcode < 0)
        free(fat);
    else
        *out_fat = fat;
    return retcode;
}

static int fsck_notes(fsck_ctx_t *ctx, cpakfs_id_t* fsid, cpakfs_fat_entry_t *fat)
{
    int fat_size = be16(fsid->bank_size_msb) & 0xFF00;
    int reserved = 1 + (fat_size >> 8) * 2 + 2; // Reserved pages: ID sector, two FAT copies, note table
    const int note_start = 0x100 + fat_size * 2;
    uint16_t note_dirty = 0;

    // Read all notes
    cpakfs_note_t notes[MAX_NOTES];
    if (block_read(ctx->port, note_start, notes, sizeof(notes)) < 0)
        return -1;

    for (int i=0; i<MAX_NOTES; i++) {
        cpakfs_note_t *note = &notes[i];
        uint16_t status = be16(note->status);
        if (!(status & NOTE_STATUS_OCCUPIED))
            continue;

        // Gamecode and pubcode are ASCII most of the time, but Datel Gameshark
        // saves binary codes in there. So what we just consider as invalid
        // is full zeros.
        if (note->gamecode[0] == 0 && note->gamecode[1] == 0 &&
            note->gamecode[2] == 0 && note->gamecode[3] == 0) {
            if (ctx->report) ctx->report(CPAKFS_ISSUE_NOTE_INVALID_GAMECODE, CPAKFS_LEVEL_ERROR,
                    "Note %d has invalid gamecode: %02x%02x%02x%02x", i,
                    note->gamecode[0], note->gamecode[1],
                    note->gamecode[2], note->gamecode[3]);
            if (ctx->mode == MODE_FIX) {
                memset(note, 0, sizeof(cpakfs_note_t));
                note_dirty |= (1 << i);
            }
        }

        if (note->pubcode[0] == 0 && note->pubcode[1] == 0) {
            if (ctx->report) ctx->report(CPAKFS_ISSUE_NOTE_INVALID_PUBCODE, CPAKFS_LEVEL_ERROR,
                    "Note %d has invalid publisher code: %02x%02x", i,
                    note->pubcode[0], note->pubcode[1]);
            if (ctx->mode == MODE_FIX) {
                memset(note, 0, sizeof(cpakfs_note_t));
                note_dirty |= (1 << i);
            }
        }
    }

    return 0;
}


int cpak_fsck(joypad_port_t port, bool fix_errors, cpakfs_report_fn report)
{
    int err;

    joypad_accessory_type_t type = joypad_get_accessory_type(port);
    if (type != JOYPAD_ACCESSORY_TYPE_CONTROLLER_PAK) {
        errno = ENODEV;
        return -1;
    }

    fsck_ctx_t ctx = {
        .port = port,
        .mode = fix_errors ? MODE_FIX : MODE_CHECK,
        .report = report,
    };

    // Check and fix the sector ID
    cpakfs_id_t fsid;
    err = fsck_fsid(&ctx, &fsid);
    if (err < 0) return err;

    // Check and fix the FAT
    cpakfs_fat_entry_t *fat = NULL;
    err = fsck_fat(&ctx, &fsid, &fat);
    if (err < 0) return err;

    // Check and fix notes
    err = fsck_notes(&ctx, &fsid, fat);
    if (err < 0) return err; 

    free(fat);
    return 0;
}

int cpak_format(joypad_port_t port, bool erase)
{
    joypad_accessory_type_t type = joypad_get_accessory_type(port);
    if (type != JOYPAD_ACCESSORY_TYPE_CONTROLLER_PAK) {
        errno = ENODEV;
        return -1;
    }

    // Detect the number of banks
    int num_banks = probe_banks(port);
    if (num_banks < 0) return -1;

    // Create a new fresh ID sector
    cpakfs_id_t fsid;
    fsid_new(&fsid, num_banks);

    // Emtpy page to write
    uint8_t empty[PAGE_SIZE] = {0};

    // Write the whole ID page. Write fsid only in the blocks that are supposed
    // to contain it, otherwise just clear.
    for (int i=0; i<8; i++) {
        uint8_t *data = (0x5A & (1<<i)) ? fsid.data8 : empty;
        if (block_write(port, i * BLOCK_SIZE, data, BLOCK_SIZE) < 0)
            return -1;
    }

    // First page of the FAT shows reserved pages
    int fat_size = be16(fsid.bank_size_msb) & 0xFF00;
    cpakfs_fat_entry_t fat[128];
    int reserved = 1 + (fat_size >> 8) * 2 + 2;

    for (int i=0; i<reserved; i++)
        fat[i] = FAT_RESERVED;
    for (int i=reserved; i<128; i++)
        fat[i] = FAT_UNUSED;

    uint8_t checksum = fat_page_checksum(fat, 1);
    fat[0] = (cpakfs_fat_entry_t){0, checksum};

    // Write the FAT to both copies
    if (block_write(port, 0x100 + 0*fat_size, fat, PAGE_SIZE) < 0)
        return -1;
    if (block_write(port, 0x100 + 1*fat_size, fat, PAGE_SIZE) < 0)
        return -1;

    // Now write subsequent pages as empty
    if (num_banks > 1) {
        for (int i=0; i<reserved; i++)
            fat[i] = FAT_UNUSED;
        checksum = fat_page_checksum(fat, 1);
        fat[0] = (cpakfs_fat_entry_t){0, checksum};

        for (int i=1; i<num_banks; i++) {
            if (block_write(port, 0x100 + 0*fat_size + i*PAGE_SIZE, fat, PAGE_SIZE) < 0)
                return -1;
            if (block_write(port, 0x100 + 1*fat_size + i*PAGE_SIZE, fat, PAGE_SIZE) < 0)
                return -1;
        }
    }

    // Finally, write the note table as fully empty.
    if (block_write(port, 0x100 + 2*fat_size + 0*PAGE_SIZE, empty, PAGE_SIZE) < 0)
        return -1;
    if (block_write(port, 0x100 + 2*fat_size + 1*PAGE_SIZE, empty, PAGE_SIZE) < 0)
        return -1;

    if (erase) {
        // Erase all pages in all banks
        int addr = 0x100 + 2*fat_size + 2*PAGE_SIZE;
        int end = num_banks * BANK_SIZE;

        while (addr < end) {
            if (block_write(port, addr, empty, PAGE_SIZE) < 0)
                return -1;
            addr += PAGE_SIZE;
        }
    }

    return 0;
}
