language: node_js

services:
  - docker

node_js:
  - "node"

sudo: false

os:
  - linux

install:
  - npm install

script:
  - npm run download
  - npm run make
  - npm run make install
  - npm run make examples

deploy:
  skip_cleanup: true
  provider: script
  script: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && npm publish
  on:
    branch: master
    repo: anacierdem/libdragon
    tags: true