#ifndef TEST_RSPQ_CONSTANTS
#define TEST_RSPQ_CONSTANTS

#define TEST_RSPQ_BIG_COMMAND_SIZE      62
#define TEST_RSPQ_BIG_PAYLOAD_WORDS     (TEST_RSPQ_BIG_COMMAND_SIZE-1)
#define TEST_RSPQ_BIG_PAYLOAD_SIZE      (TEST_RSPQ_BIG_PAYLOAD_WORDS*4)

#endif
