##########################################################################
# RSP QUEUE UCODE
##########################################################################
#
# The documentation for the RSP Queue engine is in rspq.h (API) and
# rspq.c (implementation). The latter contains an architectural overview
# that also describes the behavior of this ucode.
#
##########################################################################

#include <rsp_queue.inc>
