#ifndef __RSPQ_INTERNAL
#define __RSPQ_INTERNAL

#define RSPQ_DEBUG 1

#define RSPQ_DRAM_LOWPRI_BUFFER_SIZE   0x1000
#define RSPQ_DRAM_HIGHPRI_BUFFER_SIZE  0x80

#define RSPQ_DMEM_BUFFER_SIZE          0x100
#define RSPQ_OVERLAY_TABLE_SIZE        0x10
#define RSPQ_OVERLAY_DESC_SIZE         0x10
#define RSPQ_MAX_OVERLAY_COUNT         8

// Minimum / maximum size of a block's chunk (contiguous memory buffer)
#define RSPQ_BLOCK_MIN_SIZE            64
#define RSPQ_BLOCK_MAX_SIZE            4192

// Maximum number of nested block calls
#define RSPQ_MAX_BLOCK_NESTING_LEVEL 8
#define RSPQ_LOWPRI_CALL_SLOT        (RSPQ_MAX_BLOCK_NESTING_LEVEL+0)
#define RSPQ_HIGHPRI_CALL_SLOT       (RSPQ_MAX_BLOCK_NESTING_LEVEL+1)


#define SP_STATUS_SIG_SYNCPOINT               SP_STATUS_SIG2
#define SP_WSTATUS_SET_SIG_SYNCPOINT          SP_WSTATUS_SET_SIG2
#define SP_WSTATUS_CLEAR_SIG_SYNCPOINT        SP_WSTATUS_CLEAR_SIG2

#define SP_STATUS_SIG_HIGHPRI_RUNNING         SP_STATUS_SIG3
#define SP_WSTATUS_SET_SIG_HIGHPRI_RUNNING    SP_WSTATUS_SET_SIG3
#define SP_WSTATUS_CLEAR_SIG_HIGHPRI_RUNNING  SP_WSTATUS_CLEAR_SIG3

#define SP_STATUS_SIG_HIGHPRI                 SP_STATUS_SIG4
#define SP_WSTATUS_SET_SIG_HIGHPRI            SP_WSTATUS_SET_SIG4
#define SP_WSTATUS_CLEAR_SIG_HIGHPRI          SP_WSTATUS_CLEAR_SIG4

#define SP_STATUS_SIG_BUFDONE_HIGH            SP_STATUS_SIG5
#define SP_WSTATUS_SET_SIG_BUFDONE_HIGH       SP_WSTATUS_SET_SIG5
#define SP_WSTATUS_CLEAR_SIG_BUFDONE_HIGH     SP_WSTATUS_CLEAR_SIG5

#define SP_STATUS_SIG_BUFDONE_LOW             SP_STATUS_SIG6
#define SP_WSTATUS_SET_SIG_BUFDONE_LOW        SP_WSTATUS_SET_SIG6
#define SP_WSTATUS_CLEAR_SIG_BUFDONE_LOW      SP_WSTATUS_CLEAR_SIG6

#define SP_STATUS_SIG_MORE                    SP_STATUS_SIG7
#define SP_WSTATUS_SET_SIG_MORE               SP_WSTATUS_SET_SIG7
#define SP_WSTATUS_CLEAR_SIG_MORE             SP_WSTATUS_CLEAR_SIG7

// RSP assert codes
#define ASSERT_INVALID_OVERLAY       0x0001
#define ASSERT_INVALID_COMMAND       0x0002
#define ASSERT_GP_BACKWARD           0x0003

#endif
