/*
    x264_amalgam_config: shared config macros for x264 amalgam units
*/
#ifndef LIBDRAGON_X264_AMALGAM_CONFIG_H
#define LIBDRAGON_X264_AMALGAM_CONFIG_H

#include <stdint.h>
#include "x264_config.h"

typedef struct x264_t x264_t;

// Configuration macros (normally generated by x264's configure).
#define HAVE_MALLOC_H 0
#define HAVE_THP 0
#define HAVE_LOG2F 1
#define HAVE_STRTOK_R 1
#define HAVE_CLOCK_GETTIME 0
#define HAVE_MMAP 0

#define HAVE_GPL 1
#define HAVE_OPENCL 0
#define HAVE_INTERLACED 0

#define HAVE_THREAD 0
#define HAVE_POSIXTHREAD 0
#define HAVE_WIN32THREAD 0
#define HAVE_BEOSTHREAD 0
#define HAVE_WINRT 0
#define HAVE_CPU_COUNT 0

#define HAVE_MMX 0
#define HAVE_X86_INLINE_ASM 0
#define HAVE_VECTOREXT 0
#define HAVE_ALTIVEC 0
#define HAVE_ALTIVEC_H 0
#define HAVE_VSX 0
#define HAVE_NEON 0
#define HAVE_ARMV6 0
#define HAVE_ARMV6T2 0
#define HAVE_AARCH64 0
#define HAVE_SVE 0
#define HAVE_SVE2 0
#define HAVE_LSX 0
#define HAVE_MSA 0
#define HAVE_INTEL_DISPATCHER 0

#define HAVE_BITDEPTH8 1
#define HAVE_BITDEPTH10 0

#if defined(_WIN32) || defined(__MINGW32__)
#define SYS_WINDOWS 1
#define SYS_LINUX 0
#define SYS_FREEBSD 0
#define SYS_NETBSD 0
#define SYS_OPENBSD 0
#define SYS_S 0
#define SYS_BEOS 0
#define SYS_CYGWIN 0
#define SYS_MACOSX 0
#elif defined(__APPLE__)
#define SYS_WINDOWS 0
#define SYS_LINUX 0
#define SYS_FREEBSD 0
#define SYS_NETBSD 0
#define SYS_OPENBSD 0
#define SYS_S 0
#define SYS_BEOS 0
#define SYS_CYGWIN 0
#define SYS_MACOSX 1
#elif defined(__linux__)
#define SYS_WINDOWS 0
#define SYS_LINUX 1
#define SYS_FREEBSD 0
#define SYS_NETBSD 0
#define SYS_OPENBSD 0
#define SYS_S 0
#define SYS_BEOS 0
#define SYS_CYGWIN 0
#define SYS_MACOSX 0
#else
#define SYS_WINDOWS 0
#define SYS_LINUX 0
#define SYS_FREEBSD 0
#define SYS_NETBSD 0
#define SYS_OPENBSD 0
#define SYS_S 0
#define SYS_BEOS 0
#define SYS_CYGWIN 0
#define SYS_MACOSX 0
#endif

#define ARCH_X86 0
#define ARCH_X86_64 0
#define ARCH_ARM 0
#define ARCH_AARCH64 0
#define ARCH_PPC 0
#define ARCH_MIPS 0
#define ARCH_LOONGARCH 0

#define BIT_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X264_AMALGAM_NO_SEI 1

#ifndef CHROMA_FORMAT
#define CHROMA_FORMAT X264_CHROMA_FORMAT
#endif

// Avoid macro clash with Darwin's ALIGN() in sys/param.h
#ifdef ALIGN
#undef ALIGN
#endif

#endif

