name: "Git diff"
description: "Compares provided paths (optional) for given git refs/commits."
inputs:
  base:
    description: "Base commit or ref to compare"
    required: true
  head:
    description: "Head commit or ref to compare"
    required: true
  paths:
    description: "Paths to compare"
    required: false
    default: ./Dockerfile ./tools/build-toolchain.sh
outputs:
  changed:
    value: ${{ steps.path_change.outputs.exitCode }}
    description: "1 if files changed, 0 otherwise. Any other value is an error."
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Compare paths on base with head
      id: path_change
      shell: bash {0}
      run: |
        git diff --exit-code -s \
        ${{ inputs.base }} \
        ${{ inputs.head }} \
        -- ${{ inputs.paths }}
        echo "exitCode=$?" >> $GITHUB_OUTPUT
