all: audioplayer cpptest ctest dfsdemo fontdemo gldemo mixertest mptest mputest rdpqdemo rspqdemo spritemap test timers vrutest vtest pixelshader eepromfstest
clean: audioplayer-clean cpptest-clean ctest-clean dfsdemo-clean fontdemo-clean gldemo-clean mixertest-clean mptest-clean mputest-clean rdpqdemo-clean rspqdemo-clean spritemap-clean test-clean timers-clean vrutest-clean vtest-clean pixelshader-clean eepromfstest-clean

audioplayer:
	$(MAKE) -C audioplayer
audioplayer-clean:
	$(MAKE) -C audioplayer clean

cpptest:
	$(MAKE) -C cpptest
cpptest-clean:
	$(MAKE) -C cpptest clean

ctest:
	$(MAKE) -C ctest
ctest-clean:
	$(MAKE) -C ctest clean

dfsdemo:
#	Commented for now, because it requires mikmod
#	$(MAKE) -C dfsdemo
dfsdemo-clean:
	$(MAKE) -C dfsdemo clean

eepromfstest:
	$(MAKE) -C eepromfstest
eepromfstest-clean:
	$(MAKE) -C eepromfstest clean

fontdemo:
	$(MAKE) -C fontdemo
fontdemo-clean:
	$(MAKE) -C fontdemo clean

gldemo:
	$(MAKE) -C gldemo
gldemo-clean:
	$(MAKE) -C gldemo clean

mixertest:
	$(MAKE) -C mixertest
mixertest-clean:
	$(MAKE) -C mixertest clean

mptest:
	$(MAKE) -C mptest
mptest-clean:
	$(MAKE) -C mptest clean

mputest:
	$(MAKE) -C mputest
mputest-clean:
	$(MAKE) -C mputest clean

rdpqdemo:
	$(MAKE) -C rdpqdemo
rdpqdemo-clean:
	$(MAKE) -C rdpqdemo clean

rspqdemo:
	$(MAKE) -C rspqdemo
rspqdemo-clean:
	$(MAKE) -C rspqdemo clean

rtctest:
	$(MAKE) -C rtctest
rtctest-clean:
	$(MAKE) -C rtctest clean

spritemap:
	$(MAKE) -C spritemap
spritemap-clean:
	$(MAKE) -C spritemap clean

test:
	$(MAKE) -C test
test-clean:
	$(MAKE) -C test clean

timers:
	$(MAKE) -C timers
timers-clean:
	$(MAKE) -C timers clean

vrutest:
	$(MAKE) -C vrutest
vrutest-clean:
	$(MAKE) -C vrutest clean

vtest:
	$(MAKE) -C vtest
vtest-clean:
	$(MAKE) -C vtest clean

pixelshader:
	$(MAKE) -C pixelshader
pixelshader-clean:
	$(MAKE) -C pixelshader clean

.PHONY: audioplayer audioplayer-clean cpptest cpptest-clean ctest ctest-clean dfsdemo dfsdemo-clean fontdemo fontdemo-clean gldemo gldemo-clean mixertest mixertest-clean mptest mptest-clean mputest mputest-clean spritemap spritemap-clean
.PHONY: rdpqdemo rdpqdemo-clean rspqdemo rspqdemo-clean test test-clean timers timers-clean vrutest vrutest-clean vtest vtest-clean pixelshader pixelshader-clean eepromfstest eepromfstest-clean
