/**
 * @file rsph264_internal.h
 * @author Giovanni Bajo <giovannibajo@gmail.com>
 */
/*
 * RSPH264 - low-level interface library to RSP ucode
 *
 * This library is used internally by the H264 player
 * to initialize and communicate with the RSP ucode. It
 * is not meant for high-level usage.
 *
 */

#ifndef RSPH264_H
#define RSPH264_H

#include <stdint.h>
#include <assert.h>

/***********************************************************
 * Main API.
 ***********************************************************/

// Initialize RSPH264 library (call it once)
void rsph264_init(void);

// Start working on a frame. This function uploads the ucode
// to RSP and starts RSP processing.
void rsph264_begin_frame(void);

// Sync RSP: wait for currently queued functions to terminate.
// This can be used to force sync points in which all previously enqueued
// tasks have been performed, but obviously wastes CPU cycles.
// It should be used only for debugging purposes.
void rsph264_sync(void);


/***********************************************************
 * Profiling.
 *
 * Set RSPH264_PROFILE to 1 to count the commands and the overlay switches
 * generated by this module, and to log them per frame together with the RSP
 * DMA traffic measured through the emux profiler (see h264.c).
 *
 * This is off by default because the per-frame logging drains the RSP pipeline
 * at every frame boundary, to attribute the traffic to the frame that caused
 * it, and so perturbs the very timings it measures.
 ***********************************************************/

#ifndef RSPH264_PROFILE
#define RSPH264_PROFILE   0
#endif

#if RSPH264_PROFILE

// Statistics on the RSP command stream produced by this module.
//
// These count what the CPU wrote into the rspq queue, not what the RSP
// actually did: overlay switches caused by other subsystems preempting us
// through the highpri queue are not visible here.
//
// Overlay switches are the dominant source of RSP DMA traffic in the H264
// decoder (each one reloads a few KiB of IMEM and DMEM), so this counter is
// the main knob to watch when optimizing memory bandwidth.
// Index into the per-overlay arrays below.
#define RSPH264_STAT_INTER   0
#define RSPH264_STAT_INTRA   1

typedef struct {
	uint32_t commands;        // Commands written into the queue
	uint32_t ovl_switches;    // Commands that forced an overlay switch
	// Same two counters split per overlay: cmds[i] counts the commands sent to
	// overlay i, switches_to[i] the switches that made it the current one.
	// Together they say how the command stream is partitioned, which is what
	// tells whether reordering the macroblocks could merge more runs.
	uint32_t cmds[2];
	uint32_t switches_to[2];
} rsph264_stats_t;

void rsph264_stats_reset(void);
void rsph264_stats_get(rsph264_stats_t *stats);

// Average DMA bytes that one overlay switch costs, measured at runtime by
// issuing no-op commands that do nothing but force switches back and forth.
// Needs an emux-capable emulator; returns 0 elsewhere.
uint32_t rsph264_measure_overlay_switch_cost(void);

#endif


/***********************************************************
 * Task queueing API.
 *
 * These functions enqueue a new task for execution by RSP.
 * The task will be performed in background as soon as the RSP
 * finishes previously enqueued tasks.
 *
 * Tasks are strictly executed in enqueued order, as they might
 * depend one on each other.
 ***********************************************************/

// Cache flag: Do not force cache writeback of source buffer
#define RSPH264_CACHE_SKIP_SOURCE  (1<<0)

// Cache flag: Do not force cache invalidation of destination buffer
#define RSPH264_CACHE_SKIP_DEST    (1<<1)

// Cache flag: Do not force cache writeback/invalidate at all
#define RSPH264_CACHE_SKIP_ALL     (RSPH264_CACHE_SKIP_SOURCE | RSPH264_CACHE_SKIP_DEST)


void rsph264_queue_interpolate_luma(
	int cache_flags,
	const uint8_t *src, uint32_t src_pitch,
	uint8_t *dst, uint32_t dst_pitch,
	uint32_t width, uint32_t height,
	uint32_t dx, uint32_t dy);

void rsph264_queue_interpolate_chroma(
	int cache_flags,
	const uint8_t *src, uint32_t src_pitch,
	uint8_t *dst, uint32_t dst_pitch,
	uint32_t width, uint32_t height,
	uint32_t dx, uint32_t dy);

void rsph264_queue_interpolate_luma_overfill(
    int cache_flags,
    const uint8_t *frame, uint32_t frame_pitch,
    uint8_t *dst, uint32_t dst_pitch,
    uint32_t frame_size,
    uint32_t block_size,
    uint32_t mv, uint32_t pos);

void rsph264_queue_interpolate_chroma_overfill(
    int cache_flags,
    const uint8_t *frame, uint32_t frame_pitch,
    uint8_t *dst, uint32_t dst_pitch,
    uint32_t frame_size,
    uint32_t block_size,
    uint32_t mv, uint32_t pos);

void rsph264_queue_interpolate_all_overfill(
    int cache_flags,
    const uint8_t *frame, uint32_t frame_pitch,
    uint8_t *dst_luma, uint8_t *dst_chroma_1, uint8_t *dst_chroma_2, uint32_t dst_pitch,
    uint32_t frame_size,
    uint32_t block_size,
    uint32_t mv, uint32_t pos);

void rsph264_queue_intrapred_chroma_8x8(
    int cache_flags,
    const uint8_t *src_l, const uint8_t *src_u, const uint8_t *src_ul,
    uint8_t *dst, uint32_t left_pitch, uint32_t dst_pitch,
    uint32_t mode, uint32_t availability);

// Packed weightp coefficients of a plane whose prediction must be left
// untouched (weight 1, offset 0, denominator 0). The RSP detects this value
// and skips the weighting pass altogether.
#define RSPH264_WEIGHT_IDENTITY   0x01000000

// Pack the explicit weighted prediction coefficients of one plane into the
// format expected by rsph264_queue_set_weights_if_changed(). The denominator
// is folded into the weight, and the offset is pre-shifted to the precision
// used by the RSP (see ApplyWeight in rsph264_inter.S).
static inline uint32_t rsph264_weight_pack(int weight, int offset, int denom)
{
	// The bitstream can only code weights in [-128,127], but the default weight
	// used when a reference has no explicit weights is 1<<denom, that is 128
	// when denom is 7 (the denominator normally used by x264).
	assert(weight >= -128 && weight <= 128);
	assert(offset >= -128 && offset <= 127);
	assert(denom >= 0 && denom <= 7);

	if (weight == (1 << denom) && offset == 0)
		return RSPH264_WEIGHT_IDENTITY;

	uint32_t kw = (uint32_t)(weight * (1 << (8 - denom))) & 0xFFFF;
	uint32_t ko = (uint32_t)(offset * 128) & 0xFFFF;
	return (kw << 16) | ko;
}

// Configure the weightp coefficients used by subsequent interpolation tasks,
// for the three planes. The coefficients must be packed with
// rsph264_weight_pack(). The command is sent to the RSP only when the
// coefficients actually change, so this can be called for every partition.
void rsph264_queue_set_weights_if_changed(
	uint32_t luma, uint32_t cb, uint32_t cr);

void rsph264_queue_set_packed_delta_buffer(
	int cache_flags,
	const uint8_t *src);

void rsph264_queue_set_packed_delta_buffer_if_changed(
	int cache_flags,
	const uint8_t *src);

void rsph264_queue_reset_packed_delta_buffer(void);

const uint8_t* rsph264_cur_delta_buffer(const uint8_t *buf);

void rsph264_queue_dequant_transform_residual(
	int cache_flags,
	uint8_t *dst, uint32_t dst_pitch,
	const int16_t *dc, uint32_t qp, uint32_t ac);

void rsph264_queue_transform_dequant_chromadc(
	int cache_flags,
	int16_t *dst, uint32_t qp);

void rsph264_queue_process_luma_inter_residual(
	int cache_flags,
	uint8_t *dst, uint32_t dst_pitch,
	const int16_t *dc, uint32_t qp, uint32_t totalCoeffMask);

void rsph264_queue_process_chroma_residual(
	int cache_flags,
	uint8_t *dst1, uint8_t *dst2, uint32_t dst_pitch,
	uint32_t qp, uint32_t totalCoeffMask);

void rsph264_queue_process_luma_intra4_residual(
    int cache_flags,
    const uint8_t *src, uint8_t *dst,
    uint32_t src_pitch, uint32_t dst_pitch,
    const uint8_t *modeAvail,
    uint32_t qp, uint32_t totalCoeffMask);

void rsph264_queue_process_luma_intra16_residual(
    int cache_flags,
    const uint8_t *src, uint8_t *dst,
    uint32_t src_pitch, uint32_t dst_pitch,
    const uint32_t mode, const uint32_t availability,
    uint32_t qp, uint32_t totalCoeffMask);

void rsph264_queue_write_macroblock(
	int cache_flags,
	const uint8_t *src,
	uint8_t *dst_luma, uint8_t *dst_cb, uint8_t *dst_cr,
	uint32_t mb_width);

void rsph264_queue_set_cavlc_buffer(
	int cache_flags,
	const uint8_t *src,
    uint8_t bitOff);

void rsph264_queue_set_cavlc_buffer_if_changed(
    int cache_flags,
    const uint8_t *src,
    uint8_t bitOff);

void rsph264_queue_decode_coeffs_pair_cavlc(
    int cache_flags,
    uint8_t nc,
    uint8_t maxcoeffs);

void rsph264_queue_decode_coeffs_pair_cavlc(
    int cache_flags,
    uint8_t nc,
    uint8_t maxcoeffs);

void rsph264_queue_decode_chromadc_coeffs_pair_cavlc(
    int cache_flags
);

int rsph264_DEBUG_cavlc(uint8_t* packed_delta, int *len, uint8_t *numCoeffs, uint8_t *totalZeroes);

void rsph264_queue_decode_residual(
    int cache_flags,
    uint8_t *packedCoeff, uint8_t *totalCoeff, 
    const uint8_t *totalCoeffLeft, const uint8_t *totalCoeffUp,
    uint32_t codedBlockPattern, int is16x16
);

int rsph264_cur_cavlc_buffer(const uint8_t **ptr, int *bitOff);

// debugging functions (only for tests)
void rsph264_queue_debug_random_status(void);
void rsph264_queue_debug_load_overlay(const char* ovlname);

#endif
