#ifndef __LIBDRAGON_YUV_INTERNAL_H
#define __LIBDRAGON_YUV_INTERNAL_H

#define ASSERT_INVALID_INPUT_Y   0x0001
#define ASSERT_INVALID_INPUT_CB  0x0002
#define ASSERT_INVALID_INPUT_CR  0x0003
#define ASSERT_INVALID_OUTPUT    0x0004

#define BLOCK_W 32
#define BLOCK_H 16

#endif
