# Build and push a docker image whenever toolchain script is updated. It is
# important that this workflow always runs to be able to trigger the default
# branch ci check.
name: Docker Build

on:
  push:
    branches:
      - trunk

jobs:
  Build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Compare toolchain build script to github.event.before and skip the build
      # if it did not change.
      - name: Compare files to default branch
        uses: ./.github/actions/path-diff
        id: path_diff
        with:
          base: ${{ github.event.before }}
          head: ${{ github.sha }}

      - name: Set up Docker Buildx
        if: ${{ steps.path_diff.outputs.changed == 1 }}
        uses: docker/setup-buildx-action@v1

      - name: Log in to the container registry
        if: ${{ steps.path_diff.outputs.changed == 1 }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Create a lower cased version of the repo name. This is required
      # because Docker supports only lowercase names in the registry, while
      # a repo name on GitHub can have uppercase letters.
      - name: Downcase repository name
        run: |
          echo "GITHUB_REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push
        if: ${{ steps.path_diff.outputs.changed == 1 }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${GITHUB_REPOSITORY_LOWERCASE}:${{ github.sha }}
            ghcr.io/${GITHUB_REPOSITORY_LOWERCASE}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
