# Build and push a docker image whenever toolchain script is updated. It is
# important that this workflow always runs to be able to trigger the default
# branch ci check.
name: Docker Build

on:
  push:
    branches:
      - trunk

jobs:
  Build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Compare toolchain build script to github.event.before and skip the build
      # if it did not change.
      - name: Compare build-toolchain.sh to default branch
        id: toolchain_change
        shell: bash {0}
        continue-on-error: true
        run: |
          git diff --exit-code -s \
          ${{ github.event.before }} \
          ${{ github.sha }} \
          ./tools/build-toolchain.sh
          echo "::set-output name=exitCode::$?"

      - name: Set up Docker Buildx
        if: ${{ steps.toolchain_change.outputs.exitCode == 1 }}
        uses: docker/setup-buildx-action@v1

      - name: Log in to the container registry
        if: ${{ steps.toolchain_change.outputs.exitCode == 1 }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.toolchain_change.outputs.exitCode == 1 }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/libdragon:${{ github.sha }}
            ghcr.io/${{ github.actor }}/libdragon:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
